spring.application.name=TeamTrack

#basic auth credentials
spring.security.user.name=lawrence
spring.security.user.password=pass

#H2 Configurations
spring.datasource.url=jdbc:h2:mem:testdb
spring.h2.console.enabled=true
spring.sql.init.data-locations=classpath:team_track.sql
spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=true
